#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  scripts/select_distro_wrapper.sh [auto]
  scripts/select_distro_wrapper.sh noetic
  scripts/select_distro_wrapper.sh humble
  scripts/select_distro_wrapper.sh status
  scripts/select_distro_wrapper.sh clear

Select which sibling wrapper package is visible to the active workspace tools.

Modes:
  auto   Select from ROS_VERSION. This is the default when no mode is given.
  noetic Hide humble/ from catkin. Use before Noetic catkin builds.
  humble Hide noetic/ from colcon/ament. Use before Humble colcon builds.
  status Print current marker state.
  clear  Remove generated ignore markers.

The generated markers are ignored by git and should stay local workspace state.
USAGE
}

if [[ $# -gt 1 ]]; then
  usage >&2
  exit 2
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"

noetic_colcon_ignore="${repo_root}/noetic/COLCON_IGNORE"
noetic_ament_ignore="${repo_root}/noetic/AMENT_IGNORE"
humble_catkin_ignore="${repo_root}/humble/CATKIN_IGNORE"
selection_file="${repo_root}/.distro_wrapper_selection"

clear_markers() {
  rm -f "${noetic_colcon_ignore}" "${noetic_ament_ignore}" "${humble_catkin_ignore}" "${selection_file}"
}

write_marker() {
  local path="$1"
  local text="$2"
  printf '%s\n' "${text}" > "${path}"
}

select_noetic() {
  clear_markers
  write_marker "${humble_catkin_ignore}" "Generated by scripts/select_distro_wrapper.sh noetic. Hide Humble wrapper from catkin."
  write_marker "${selection_file}" "noetic"
  echo "Selected Noetic wrapper: noetic/ is visible, humble/ is hidden from catkin."
}

select_humble() {
  clear_markers
  write_marker "${noetic_colcon_ignore}" "Generated by scripts/select_distro_wrapper.sh humble. Hide Noetic wrapper from colcon."
  write_marker "${noetic_ament_ignore}" "Generated by scripts/select_distro_wrapper.sh humble. Hide Noetic wrapper from ament tools."
  write_marker "${selection_file}" "humble"
  echo "Selected Humble wrapper: humble/ is visible, noetic/ is hidden from colcon/ament."
}

auto_select() {
  case "${ROS_VERSION:-}" in
    1)
      select_noetic
      ;;
    2)
      select_humble
      ;;
    *)
      echo "ROS_VERSION is not set to 1 or 2; source /opt/ros/<distro>/setup.bash or pass noetic/humble explicitly." >&2
      exit 2
      ;;
  esac
}

marker_state() {
  local selected="none"
  if [[ -f "${selection_file}" ]]; then
    selected="$(<"${selection_file}")"
  fi
  echo "selection=${selected}"
  for path in "${noetic_colcon_ignore}" "${noetic_ament_ignore}" "${humble_catkin_ignore}"; do
    if [[ -e "${path}" ]]; then
      echo "present ${path#${repo_root}/}"
    else
      echo "absent  ${path#${repo_root}/}"
    fi
  done
}

mode="${1:-auto}"
case "${mode}" in
  auto)
    auto_select
    ;;
  noetic)
    select_noetic
    ;;
  humble)
    select_humble
    ;;
  status)
    marker_state
    ;;
  clear)
    clear_markers
    echo "Cleared generated distro wrapper selection markers."
    ;;
  -h|--help|help)
    usage
    ;;
  *)
    usage >&2
    exit 2
    ;;
esac
